# Generated by Django 3.2.8 on 2021-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetxmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='expense',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='spent',
            field=models.IntegerField(),
        ),
    ]
