# Generated by Django 3.2.8 on 2021-10-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetxmaster', '0002_auto_20211016_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='Budget',
        ),
    ]
